name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v1

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: install dependencies
        run: npm install

      - name: run weather update script
        run: npm run update
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY}}

      - name: commit and push
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
